FROM node:22.16.0-slim
WORKDIR /devsonic.cl
COPY ./package.json /devsonic.cl/
COPY ./angular.json /devsonic.cl/
COPY ./tsconfig.json /devsonic.cl/
COPY ./tsconfig.app.json /devsonic.cl/
COPY ./tsconfig.spec.json /devsonic.cl/
RUN npm install
CMD ["npm", "run", "watch"]
